name: mmmm
channels:
- conda-forge
- pytorch
- nvidia
- defaults
dependencies:
- python=3.11
- numpy
- scikit-learn
- pytorch::pytorch=2.2.2
- pytorch::pytorch-cuda=12.1
- pytorch::torchvision
- ocl-icd-system  # https://github.com/conda-forge/openvino-feedstock/pull/73
- einops
- lightning
- torchmetrics
- transformers
- peft
- sentencepiece
- timm
- wandb
- cytoolz
- llvm-openmp<16  # https://github.com/pytorch/pytorch/issues/99625
- pandas
- pyarrow  # https://github.com/pandas-dev/pandas/issues/54466
- openpyxl
- seaborn
- nibabel
- pydicom
- itk
- zstandard
- pip
- pip:
  - jsonargparse[signatures, omegaconf]
  - mashumaro[orjson]
  - pynrrd
# comment out since we do not need bitsandbytes currently, and it can cause trouble: https://github.com/huggingface/peft/issues/1665
#  - bitsandbytes  # bitsandbytes plays strangely with conda, it still depends on cudatoolkit=11.8
  - xformers -i https://download.pytorch.org/whl/cu121
