name: mmmm
channels:
- conda-forge
- pytorch
- nvidia
- defaults
dependencies:
- python=3.11
- numpy<2
- scikit-learn
- pytorch::pytorch<2.4  # vllm compatible
- pytorch::pytorch-cuda=12.1
- pytorch::torchvision
- ocl-icd-system  # https://github.com/conda-forge/openvino-feedstock/pull/73
- einops
- lightning
- monai
- torchmetrics
- transformers
- peft
- sentencepiece
- timm
- wandb
- cytoolz
- llvm-openmp<16  # https://github.com/pytorch/pytorch/issues/99625
- ninja  # to load C++ extensions
- pandas
- pyarrow  # https://github.com/pandas-dev/pandas/issues/54466
- openpyxl
- seaborn
- nibabel
- pydicom
- itk
- zstandard
- jsonargparse
- omegaconf
- mashumaro
- orjson
- pip
- pip:
  - xformers==v0.0.27 -i https://download.pytorch.org/whl/cu121  # not using PyTorch 2.4 and no pre-built binary for v0.0.27.post*
  - vllm
  - pynrrd
  - pylidc  # for LIDC data
  # for evaluation
  - evaluate
  - radgraph
  - rouge_score
  - bert_score
