name: mmmm
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - numpy
  - h5py
  - scikit-learn
  - pytorch::pytorch=2.2
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision
  - einops
  - lightning
  - torchmetrics
  - transformers
  - sentencepiece
  - timm
  - wandb
  - llvm-openmp<16  # https://github.com/pytorch/pytorch/issues/99625
  - pandas
  - pyarrow  # https://github.com/pandas-dev/pandas/issues/54466
  - openpyxl
  - seaborn
  - nibabel
  - pydicom

  - pip
  - pip:
    - cytoolz
    - jsonargparse[signatures, omegaconf, argcomplete]
    - xformers --index-url https://download.pytorch.org/whl/cu118
