data: data.yaml
tokenizer: ../tokenizer.yaml
logger: logger.yaml
trainer:
  max_steps: 100
  precision: bf16-true
optimization:
- optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-5
      weight_decay: 5e-2
  lr_scheduler:
    scheduler:
      class_path: timm.scheduler.CosineLRScheduler
      init_args:
        t_initial: ${trainer.max_steps}
        t_in_epochs: false
        warmup_t: 0
        warmup_prefix: true
    interval: step
    frequency: 200
