data: data.yaml
tokenizer: ../tokenizer.yaml
logger: logger.yaml
trainer:
  max_steps: 10000
  log_every_n_steps: 10
  precision: bf16-true
  gradient_clip_val: 10
  gradient_clip_algorithm: norm
  callbacks:
  - class_path: luolib.lightning.callbacks.ModelCheckpoint
    init_args:
      every_n_train_steps: 200
      filename: "{step}"
      save_top_k: -1
      save_last: true
      verbose: true
optimization:
- optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-5
      weight_decay: 5e-2
  lr_scheduler:
    scheduler:
      class_path: timm.scheduler.CosineLRScheduler
      init_args:
        t_initial: ${trainer.max_steps}
        t_in_epochs: false
        warmup_t: 0
        warmup_prefix: true
    interval: step
    frequency: 200
