trainer:
  max_steps: 10000
  precision: bf16-true
  gradient_clip_val: 1
  gradient_clip_algorithm: norm
#  strategy: ddp
  callbacks:
  - class_path: luolib.lightning.callbacks.ModelCheckpoint
    init_args:
      every_n_train_steps: 2000
      filename: "{step}"
      save_top_k: -1
      save_last: true
      verbose: true
optim:
  param_groups:
  - prefix: ['']
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 5e-5
      weight_decay: 0.01
  lr_scheduler:
    scheduler:
      class_path: timm.scheduler.CosineLRScheduler
      init_args:
        t_initial: ${trainer.max_steps}
        t_in_epochs: false
        warmup_t: 500
        warmup_prefix: true
    interval: step
    frequency: 250
data:
  class_path: _vqa._base.VQADataModule
  init_args:
    dataset_name: VQA-RAD
    dataloader:
      train_batch_size: 16
