max_steps: 60000
val_check_interval: 100
log_every_n_steps: 10
precision: bf16-true
gradient_clip_val: 10
gradient_clip_algorithm: norm
callbacks:
- class_path: luolib.lightning.callbacks.ModelCheckpoint
  init_args:
    every_n_train_steps: 1000
    filename: "{step}"
    save_top_k: -1
    save_last: true
    verbose: true
